hello: ENC[AES256_GCM,data:aNkl9wfvRY++zVLOS2fRV27Du75bzPTx58FVeKudnlBxQLae3aopBvSKaoX+Fw==,iv:2e1zGd4obdc/tR4NgHOPuBOtDuHwHWVDZTaU0OTa+h8=,tag:rgfRK2INAL/hC0ESaEZEVA==,type:str]
example_key: ENC[AES256_GCM,data:yk1bjyg+j1g5cD+eqA==,iv:HKkXxmdfBQ7oLGo7UBH2P96eDtq3/M5EkurFhAGaNUA=,tag:TuuHGyPom3Sx47AOqIpWLQ==,type:str]
#ENC[AES256_GCM,data:9u40ABJBn5TUs18qKXt7QQ==,iv:qH60zwUcvyEneyjDuSEx5YNofvowiatT3Kf5CVJBxLw=,tag:YcxHnWRkEarM95lPIeWPMg==,type:comment]
example_array:
    - ENC[AES256_GCM,data:n1oK2QHg3Qm+M8zdP50=,iv:dXGMi9g+E6yhXzadQ1PBwGEJlUvm6LTgE3xfYlIEta0=,tag:MtMvQUlSM+dLQ/+hen6qjg==,type:str]
    - ENC[AES256_GCM,data:kAyn/C+333o4KWfJ5q4=,iv:kRGnNwCvsDOZUW0ro+qqWoH6PaK93ebXz2rzFCqQ4UM=,tag:Bmv2Psyys6wU8riFZilBhQ==,type:str]
example_number: ENC[AES256_GCM,data:3LvX780XwmBFAQ==,iv:03B5O1g1o1TQv4BzdFWAGl/kacW4mws8qn/COdY+KKQ=,tag:PGAP00P8JvdfTNvK28eQvQ==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:67IA9w==,iv:OItOFhWkrbK18H4KsQFaz2fm2VjN2nG3ng5ys95hwbg=,tag:4pAarsVKdN01d8DeBDnXag==,type:bool]
    - ENC[AES256_GCM,data:v1wc1g==,iv:01uDMpkI2dhd9kmzYZP2jf51cbSA7NsePx8sKJ6Nmuc=,tag:GVAFaUCkGg5U704+9GldQA==,type:bool]
sops:
    age:
        - recipient: age1rxem9nf4ey78fgnxuz0w298gf34my2qtdygkt52d258v9w20m3ysk66xtn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcEx2NkRGd0djM09YcjdY
            Y1QrcitWZWN4eHFVWTAxOVJOTEFndUtyK0djCm9lTnRLUDVSNTQzQTNkTmdOUEFt
            SWs2QmlBR05qNnV6QnNrWElRREtFTmcKLS0tIGZBYkxPY1dVVXgyakNOeUExWllH
            TUVSZFFZS0w0c1gxVFppbFJSTUt4YkkKn4XRuS0bJBulbwRb3THcCvYAazMtG6Pg
            nE7pc/DvbfLIoMieSMg+jioNsyFwS9lq2UZg3L4f19I5vjyOtzHCPw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19nd3sjtpgzdyysv6md8vqz9vqexy5pafk2ex5myuhps0zz9zevps63zftx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSW9nclpldlVVK2E0MmtH
            Zk1pejNoaTdMQ0NPcDh2dEVKd2xOdFYzNlF3CndiazZmOVJpbEtwU3F2dUFUZm5X
            cDZraEZlWjFDQ3NJMWtISkphUWc4UDAKLS0tIEZ2bnpPU3R5UkQwM05TNjVWNnp2
            M3hhRFZybDVqaDkyOVlrQmZZeHQyNVEKLv9t+73WRA7xW7fl0yQ/o3ADa7vMKJJS
            1G6iKCKT5f+yLt4QiymQ9tukgsE8qil1fkU+39u2Ua7RUh7u17F9aA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T16:22:02Z"
    mac: ENC[AES256_GCM,data:dwgGFlO4fcv+nIBildapMSGlVGxQxBkCvlrYgi/8sY5KhJoJ0fqdXpq+Usb9WkXtWcN2aACHAAXq43ZmF/+bsfqghg4XRCIQihkS6T1ypTQwAA9MdSpDc7XlFuI5lUfJzdG13ma2ieBFXybUL6ZPqyFuHrTKt8WI8Z8G3KfksDg=,iv:QQXuvzyVoq9jDUofoe+Wkx7DPGhvvV20FkZwoMQ0JGM=,tag:zMhOg4lVFzDLHqKU+hNqLA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
